apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
  namespace: thomas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
#        volumeMounts:
#        - mountPath: /usr/local/apache2/htdocs
#          name: httpd-data
#      volumes:
#      - name: httpd-data
#        persistentVolumeClaim:
#          claimName: httpd-pv-claim
