apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pv-claim
  namespace: thomas
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: thomas-httpd-pv-volume
