apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pv-claim
  namespace: oscar
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: httpd-pv-volume
